[workspace]
authors = ["Nikhil Padmanabhan <nikhil.padmanabhan@gmail.com>"]
channels = ["conda-forge"]
name = "roman_disperser"
platforms = ["osx-arm64", "linux-64"]
version = "0.5.0"

[tasks]
check-jax = "python -c 'import jax; print(f\"Backend: {jax.default_backend()}\"); print(jax.devices())'"

[activation]
scripts = ["scripts/activate.sh"]

[dependencies]
python = ">=3.12, <3.13"

[pypi-dependencies]
roman_disperser = { path = ".", editable = true, extras = ["full"] }

# --- ENVIRONMENTS ---
[environments]
default = ["cpu"]
cuda = ["cuda"]

# --- FEATURES ---

[feature.cpu.dependencies]
jax = ">=0.7"

[feature.cuda]
platforms = ["linux-64"]
system-requirements = { cuda = "12" }

[feature.cuda.dependencies]
jax = ">=0.7"
jaxlib = { version = "*", build = "cuda12*" }
