#!/usr/bin/env bash
# Romanisim wrap SLURM driver: submits a 4-task array on mem-lg.
# Each task is one Python orchestrator (scripts/wrap_with_romanisim.py)
# that processes its round-robin share of FITS files via 8 concurrent
# romanisim-make-image subprocesses. Idempotent: per-file skip-if-exists.
#
# Mirrors workbench/20260505-acceptance-testing-aws/slurm_run_grism.sh in
# layout: this script is the version-controlled source; a verbatim copy
# is run from /mnt/roman-science/.../acceptance/scripts/.
#
# Layout assumed when this script lives at <ACCEPT>/scripts/:
#   <ACCEPT>/output/                 # disperser FITS (input)
#   <ACCEPT>/output_l2/              # romanisim L2 ASDF (output, sibling)
#   <ACCEPT>/logs/romanisim/         # worker stdout + per-file logs
#   <ACCEPT>/slurm-meta/             # per-submission audit
#
# Env-var hooks (all optional):
#   NUM_WORKERS    default 4 (one per mem-lg array task)
#   PARTITION      default mem-lg
#   MEM            default 120G  (peak observed ~48 GB at N=8)
#   TIME           default 05:00:00 (~3 h expected at N=8)
#   PROJ_ROOT      default /data/npadman/1-Projects/roman_disperser
#
# Per-submission audit: <ACCEPT>/slurm-meta/romanisim-<JobID>.{task.sh,env}
# Scheduler stdout:     /data/npadman/tmp/slurm-logs/romanisim/%A_%a.out
#
# Usage: bash slurm_run_romanisim.sh
set -euo pipefail

ACCEPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
INPUT_DIR="${ACCEPT_DIR}/output"
OUTPUT_DIR="${ACCEPT_DIR}/output_l2"
LOG_DIR="${ACCEPT_DIR}/logs/romanisim"
META_DIR="${ACCEPT_DIR}/slurm-meta"
SLURM_LOG=/data/npadman/tmp/slurm-logs/romanisim

[ -d "$INPUT_DIR" ] || { echo "missing $INPUT_DIR"; exit 1; }

PROJ_ROOT="${PROJ_ROOT:-/data/npadman/1-Projects/roman_disperser}"
[ -f "${PROJ_ROOT}/pixi.toml" ] || { echo "no pixi.toml under PROJ_ROOT=${PROJ_ROOT}"; exit 1; }

NUM_WORKERS="${NUM_WORKERS:-4}"
PART="${PARTITION:-mem-lg}"
MEM="${MEM:-120G}"
TIME="${TIME:-05:00:00}"

mkdir -p "$OUTPUT_DIR" "$LOG_DIR" "$META_DIR" "$SLURM_LOG"

TS=$(date +%Y%m%dT%H%M%S)
TASK_WRAPPER="${META_DIR}/_romanisim_array_task_${TS}.sh"
cat > "$TASK_WRAPPER" <<EOF
#!/usr/bin/env bash
# Generated by slurm_run_romanisim.sh at $(date -Iseconds).
# Project: ${PROJ_ROOT}
# Acceptance run: ${ACCEPT_DIR}
# One SLURM array task = one Python orchestrator processing its share
# of FITS files round-robin via 8 internal threads.
# Per-file skip-if-exists makes restarts cheap.
set -euo pipefail
WORKER_INDEX=\$((SLURM_ARRAY_TASK_ID - 1))
LOG_FILE=${LOG_DIR}/worker-\${SLURM_ARRAY_TASK_ID}.log
exec pixi run --manifest-path ${PROJ_ROOT}/pixi.toml -e romanisim \\
    python ${PROJ_ROOT}/scripts/wrap_with_romanisim.py \\
        --input-dir ${INPUT_DIR} \\
        --output-dir ${OUTPUT_DIR} \\
        --log-dir ${LOG_DIR}/per-file \\
        --num-threads 8 \\
        --worker-index \${WORKER_INDEX} \\
        --num-workers ${NUM_WORKERS} \\
        > \${LOG_FILE} 2>&1
EOF
chmod +x "$TASK_WRAPPER"

JOB=$(sbatch --parsable \
    --partition="$PART" --cpus-per-task=8 --mem="$MEM" --time="$TIME" \
    --array="1-${NUM_WORKERS}%${NUM_WORKERS}" --job-name=acc-romanisim \
    --output="${SLURM_LOG}/%A_%a.out" \
    "$TASK_WRAPPER")

META="${META_DIR}/romanisim-${JOB}"
cp "$TASK_WRAPPER" "${META}.task.sh"
{
    echo "JOB=$JOB"
    echo "ARRAY=1-${NUM_WORKERS}"
    echo "NUM_WORKERS=$NUM_WORKERS"
    echo "PARTITION=$PART"
    echo "MEM=$MEM"
    echo "TIME=$TIME"
    echo "INPUT_DIR=$INPUT_DIR"
    echo "OUTPUT_DIR=$OUTPUT_DIR"
    echo "LOG_DIR=$LOG_DIR"
    echo "PROJ_ROOT=$PROJ_ROOT"
    echo "GIT_COMMIT=$(git -C "$PROJ_ROOT" rev-parse HEAD 2>/dev/null || echo NA)"
    echo "SLURM_LOG_DIR=$SLURM_LOG"
    echo "SUBMITTED_AT=$(date -Iseconds)"
} > "${META}.env"

echo "submitted JobID=${JOB} (array 1-${NUM_WORKERS}, partition=${PART}, mem=${MEM}, time=${TIME})"
echo "  task wrapper:    ${TASK_WRAPPER}"
echo "  audit:           ${META}.env"
echo "  scheduler logs:  ${SLURM_LOG}/${JOB}_*.out"
echo "  worker logs:     ${LOG_DIR}/worker-N.log"
echo "  per-file logs:   ${LOG_DIR}/per-file/"
echo "  monitor:         squeue -j ${JOB}"
