#!/usr/bin/env bash
# SLURM driver for the SSC line-grid campaign (wave 2: lines+continuum, 30x anchor, MA table 1036). v0.13.0 rerun of the 20260724 campaign: same catalog, post sky-to-FPA + RNG fixes.
#
#   bash submit.sh sim     {stpsf|gauss} {pa000|pa010}   # gpu-med a10g, ~25-40 min
#   bash submit.sh wrap    {stpsf|gauss} {pa000|pa010}   # mem-lg, romanisim L2
#   bash submit.sh closure {stpsf|gauss} {pa000|pa010}   # cpu-lg, checker+truth
#
# Sims run from main/ (its cuda env; build_grism_image.py is identical on the
# feature branch). Wraps run from main/ (romanisim env). Closure + truth run
# from the line_test worktree (default CPU env; the checker lives on the
# feature branch). Every submission copies its generated task script and an
# .env audit file into $ROOT/slurm-meta/ (repo convention), and this driver +
# configs are mirrored verbatim into $ROOT/scripts/.
#
# Idempotence: romanisim wrap skips existing outputs; sims and closure
# overwrite their own outputs deterministically (fixed seed), so resubmits
# are safe.
set -euo pipefail

STAGE=${1:?"usage: submit.sh sim|wrap|closure stpsf|gauss pa000|pa010"}
VARIANT=${2:?"variant: stpsf|gauss"}
PA=${3:?"pa: pa000|pa010"}

HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT=/mnt/roman-science/grs/line-tests-20260731-cont
MAIN=/data/npadman/1-Projects/roman/roman_disperser/main
LINE_TEST=/data/npadman/1-Projects/roman/roman_disperser/line_test
JAX_CACHE=/data/npadman/1-Projects/roman/roman_disperser/line_test_outputs/jax-cache
GAUSS_CACHE=/data/npadman/1-Projects/roman/roman_disperser/line_test_outputs/psf_cache_gaussian
SLURM_LOG=/data/npadman/tmp/slurm-logs/line-grid
CONFIG="$HERE/config_lines_${VARIANT}.yaml"
ECSV="$HERE/pointing_${PA}.ecsv"
# build_grism_image batch mode: {ecsv_basename}_{plan}.{pass}.{seg}.{obs}.{visit}.{exp}
PDIR="$ROOT/lines_${VARIANT}/pointing_${PA}_001.001.001.001.001.001"

[ -f "$CONFIG" ] && [ -f "$ECSV" ] || { echo "missing config/ecsv"; exit 1; }
mkdir -p "$ROOT/slurm-meta" "$ROOT/scripts" "$ROOT/logs" "$SLURM_LOG"
cp -f "$HERE"/submit.sh "$HERE"/config_lines_*.yaml "$HERE"/pointing_*.ecsv \
      "$HERE"/make_truth_tables.py "$ROOT/scripts/"

if [ "$VARIANT" = gauss ] && [ "$STAGE" = sim ]; then
    # Correctness gate: a missing per-SCA Gaussian cache would be silently
    # replaced by a freshly *generated STPSF* cache, poisoning the control.
    NCACHE=$(ls "$GAUSS_CACHE"/psf_WFI??_GRISM?_*.npz 2>/dev/null | wc -l)
    [ "$NCACHE" -eq 36 ] || { echo "Gaussian cache has $NCACHE/36 files"; exit 1; }
fi

TS=$(date +%Y%m%dT%H%M%S)
TAG="${STAGE}-${VARIANT}-${PA}"
WRAPPER="$ROOT/slurm-meta/_task_${TAG}_${TS}.sh"

case "$STAGE" in
sim)
    PART=gpu-med; GRES="--gres=gpu:a10g:1"; CPUS=4; MEM=28G; TIME=01:30:00
    cat > "$WRAPPER" <<EOF
#!/usr/bin/env bash
# Generated by submit.sh at $(date -Iseconds): $TAG
set -euo pipefail
export JAX_COMPILATION_CACHE_DIR=$JAX_CACHE
cd $MAIN
exec pixi run -e cuda python scripts/build_grism_image.py \\
    --config $CONFIG \\
    --pointings $ECSV \\
    --gpu 0 \\
    --cache-dir $JAX_CACHE
EOF
    ;;
wrap)
    PART=mem-lg; GRES=""; CPUS=8; MEM=120G; TIME=03:00:00
    cat > "$WRAPPER" <<EOF
#!/usr/bin/env bash
# Generated by submit.sh at $(date -Iseconds): $TAG
set -euo pipefail
cd $MAIN
exec pixi run -e romanisim python scripts/wrap_with_romanisim.py \\
    --input-dir $PDIR \\
    --output-dir $ROOT/lines_${VARIANT}_l2/pointing_${PA}_001.001.001.001.001.001 \\
    --log-dir $ROOT/logs/romanisim-${VARIANT}-${PA} \\
    --num-threads 8
EOF
    ;;
closure)
    PART=cpu-lg; GRES=""; CPUS=4; MEM=28G; TIME=02:00:00
    cat > "$WRAPPER" <<EOF
#!/usr/bin/env bash
# Generated by submit.sh at $(date -Iseconds): $TAG
set -euo pipefail
cd $LINE_TEST
pixi run python scripts/check_line_centering.py \\
    --pointing-dir $PDIR \\
    --catalog-dir $ROOT/catalog_lines \\
    --out $PDIR/residuals.parquet
exec pixi run python $HERE/make_truth_tables.py \\
    --pointing-dir $PDIR \\
    --catalog-dir $ROOT/catalog_lines
EOF
    ;;
*)  echo "unknown stage $STAGE"; exit 1 ;;
esac
chmod +x "$WRAPPER"

# Optional DEPEND=<jobid> env var chains this stage on a prior job (afterok).
JOB=$(sbatch --parsable --partition=$PART $GRES --cpus-per-task=$CPUS \
      --mem=$MEM --time=$TIME --job-name="lg-${TAG}" \
      ${DEPEND:+--dependency=afterok:$DEPEND} \
      --output="$SLURM_LOG/%x-%j.out" "$WRAPPER")

META="$ROOT/slurm-meta/${TAG}-${JOB}"
cp "$WRAPPER" "${META}.task.sh"
{
    echo "JOB=$JOB"; echo "STAGE=$STAGE"; echo "VARIANT=$VARIANT"; echo "PA=$PA"
    echo "PARTITION=$PART"; echo "CPUS=$CPUS"; echo "MEM=$MEM"; echo "TIME=$TIME"
    echo "CONFIG=$CONFIG"; echo "ECSV=$ECSV"; echo "PDIR=$PDIR"
    echo "GIT_COMMIT_LINE_TEST=$(git -C $LINE_TEST rev-parse HEAD)"
    echo "GIT_COMMIT_MAIN=$(git -C $MAIN rev-parse HEAD)"
    echo "SUBMITTED_AT=$(date -Iseconds)"
} > "${META}.env"
echo "submitted $TAG JobID=$JOB  (audit ${META}.env; log $SLURM_LOG/lg-${TAG}-${JOB}.out)"
