#!/usr/bin/env bash
# Spectro acceptance JIT cache warmup: 5-task array, each compiles ~4 SCAs in
# parallel on its own a10g, all sharing the same on-disk JAX cache.
#
# Cold compile measured at ~170 s/SCA on this a10g (debug-grism-nan repro).
# Sequential warmup of 18 SCAs would take ~50 min; 5-way parallel splits as
# 4+4+4+3+3 = ~12 min wall (cost-equivalent: same GPU-min, less wall time).
# After this completes, the 32-task production array's JIT drops from
# ~170 s/SCA to ~15 s/SCA (cache hit), saving ~45 min/pointing.
#
# JAX disk cache is multi-writer safe (atomic temp-then-rename), and the 5
# workers compile disjoint SCA sets so there is no contention.
#
# Env-var hooks:
#   NUM_WORKERS       default 5 (matches the gpu-med a10g node count)
#   PARTITION         default gpu-med
#   GRES              default gpu:a10g:1
#   MEM               default 24G
#   TIME              default 30:00 (4 SCAs * 170 s = 12 min, padded for startup)
#   PROJ_ROOT         default /data/npadman/1-Projects/roman_disperser
#
# Audit:        ../slurm-meta/grism-warmup-<JobID>.{task.sh,env}
# Scheduler:    /data/npadman/tmp/slurm-logs/grism/%A_warmup_%a.out
#
# Usage: slurm_warmup_grism.sh
set -euo pipefail

ACCEPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
CONFIG="${ACCEPT_DIR}/config.yaml"
META_DIR="${ACCEPT_DIR}/slurm-meta"
SLURM_LOG=/data/npadman/tmp/slurm-logs/grism
# Same explicit cache dir as the production array driver.
CACHE_DIR=/data/npadman/jax-cache-grism

[ -f "$CONFIG" ] || { echo "missing $CONFIG"; exit 1; }

PROJ_ROOT="${PROJ_ROOT:-/data/npadman/1-Projects/roman_disperser}"
[ -f "${PROJ_ROOT}/pixi.toml" ] || { echo "no pixi.toml under PROJ_ROOT=${PROJ_ROOT}"; exit 1; }
mkdir -p "$CACHE_DIR"

NUM_WORKERS="${NUM_WORKERS:-5}"
PART="${PARTITION:-gpu-med}"
GRES="${GRES:-gpu:a10g:1}"
MEM="${MEM:-24G}"
TIME="${TIME:-30:00}"

mkdir -p "$META_DIR" "$SLURM_LOG"

TS=$(date +%Y%m%dT%H%M%S)
TASK_WRAPPER="${META_DIR}/_grism_warmup_task_${TS}.sh"
cat > "$TASK_WRAPPER" <<EOF
#!/usr/bin/env bash
# Generated by slurm_warmup_grism.sh at $(date -Iseconds).
# Project: ${PROJ_ROOT}
# One array task = 1 a10g compiling its share of SCAs (worker-index = TASK_ID-1).
set -euo pipefail
WORKER_INDEX=\$((SLURM_ARRAY_TASK_ID - 1))
LOG_FILE=${ACCEPT_DIR}/logs/warmup-\${SLURM_ARRAY_TASK_ID}.log
exec pixi run --manifest-path ${PROJ_ROOT}/pixi.toml -e cuda \\
    python ${PROJ_ROOT}/scripts/build_grism_image.py \\
        --config ${CONFIG} \\
        --cache-dir ${CACHE_DIR} \\
        --warmup-only \\
        --gpu 0 \\
        --worker-index \${WORKER_INDEX} \\
        --num-workers ${NUM_WORKERS} \\
        --log-file \${LOG_FILE}
EOF
chmod +x "$TASK_WRAPPER"

JOB=$(sbatch --parsable \
    --partition="$PART" --gres="$GRES" --cpus-per-task=4 --mem="$MEM" --time="$TIME" \
    --array="1-${NUM_WORKERS}%${NUM_WORKERS}" --job-name=acc-grism-warmup \
    --output="${SLURM_LOG}/%A_warmup_%a.out" \
    "$TASK_WRAPPER")

META="${META_DIR}/grism-warmup-${JOB}"
cp "$TASK_WRAPPER" "${META}.task.sh"
{
    echo "JOB=$JOB"
    echo "ARRAY=1-${NUM_WORKERS}"
    echo "NUM_WORKERS=$NUM_WORKERS"
    echo "PARTITION=$PART"
    echo "GRES=$GRES"
    echo "MEM=$MEM"
    echo "TIME=$TIME"
    echo "CONFIG=$CONFIG"
    echo "CACHE_DIR=$CACHE_DIR"
    echo "PROJ_ROOT=$PROJ_ROOT"
    echo "GIT_COMMIT=$(git -C "$PROJ_ROOT" rev-parse HEAD 2>/dev/null || echo NA)"
    echo "SLURM_LOG_DIR=$SLURM_LOG"
    echo "SUBMITTED_AT=$(date -Iseconds)"
} > "${META}.env"

echo "submitted warmup JobID=${JOB} (array 1-${NUM_WORKERS}, partition=${PART}, gres=${GRES}, mem=${MEM})"
echo "  task wrapper: ${TASK_WRAPPER}"
echo "  audit:        ${META}.env"
echo "  scheduler log: ${SLURM_LOG}/${JOB}_warmup_*.out"
echo "  app logs:      ${ACCEPT_DIR}/logs/warmup-N.log"
echo "  monitor:       squeue -j ${JOB}"
