#!/usr/bin/env bash
# Spectro acceptance SLURM driver: submit build_grism_image.py as an
# N-task array (default 5), each task a single long-running Python process
# that processes its share of pointings round-robin. Mirrors the NERSC
# workbench/20260414-acceptance-testing/run.sh layout, adapted for the
# AWS multi-node SLURM cluster.
#
# Pointings are partitioned by build_grism_image.py: worker N processes
# row indices where (idx % NUM_WORKERS == N). For 32 pointings across
# 5 workers, each worker handles 6-7 pointings serially in one process.
# Compared to a 32-task array, this skips ~27 process startups and keeps
# the JAX in-memory state warm across pointings on the same node.
#
# Layout assumed (relative to this script):
#   ../config.yaml                                 # --config
#   ../../../acceptance-testing-spectro.sim.ecsv   # --pointings
#   ../slurm-meta/                                 # per-submission audit
#
# RNG keys are derived from (seed, ECSV basename, APT identifiers), so
# any worker partitioning yields bit-identical outputs.
#
# Env-var hooks (all optional):
#   NUM_WORKERS       default 5 (matches gpu-med a10g node count). Each
#                     worker = one SLURM task = one a10g.
#   PARTITION         default gpu-med
#   GRES              default gpu:a10g:1 (g5-2xlarge: 4 CPU, 31 GB, 1xa10g)
#   MEM               default 24G (~7 GB OS margin on the 31 GB node)
#   TIME              default 14:00:00. Per-pointing wall ~1h40 cold,
#                     ~1h25 warm (validation baseline). 7 pointings/worker
#                     worst case ~12 h; 14 h leaves margin for outliers.
#   PROJ_ROOT         default /data/npadman/1-Projects/roman_disperser
#
# Per-submission audit: ../slurm-meta/grism-<JobID>.{task.sh,env}
# Scheduler stdout:     /data/npadman/tmp/slurm-logs/grism/%A_%a.out
#
# Usage: slurm_run_grism.sh
set -euo pipefail

ACCEPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
CONFIG="${ACCEPT_DIR}/config.yaml"
ECSV="$(cd "${ACCEPT_DIR}/../../.." && pwd)/acceptance-testing-spectro.sim.ecsv"
META_DIR="${ACCEPT_DIR}/slurm-meta"
SLURM_LOG=/data/npadman/tmp/slurm-logs/grism
# Explicit cache dir on the CLI so it appears in scheduler logs and audit
# files, instead of being silently picked up from config.yaml.
CACHE_DIR=/data/npadman/jax-cache-grism

[ -f "$CONFIG" ] || { echo "missing $CONFIG"; exit 1; }
[ -f "$ECSV" ]   || { echo "missing $ECSV"; exit 1; }

PROJ_ROOT="${PROJ_ROOT:-/data/npadman/1-Projects/roman_disperser}"
[ -f "${PROJ_ROOT}/pixi.toml" ] || { echo "no pixi.toml under PROJ_ROOT=${PROJ_ROOT}"; exit 1; }
mkdir -p "$CACHE_DIR"

NUM_WORKERS="${NUM_WORKERS:-5}"
PART="${PARTITION:-gpu-med}"
GRES="${GRES:-gpu:a10g:1}"
MEM="${MEM:-24G}"
TIME="${TIME:-14:00:00}"

mkdir -p "$META_DIR" "$SLURM_LOG"

# Per-submission task wrapper. Backslashed $ are deferred to runtime; bare $
# expand at submit time so the on-disk wrapper is self-contained.
TS=$(date +%Y%m%dT%H%M%S)
TASK_WRAPPER="${META_DIR}/_grism_array_task_${TS}.sh"
cat > "$TASK_WRAPPER" <<EOF
#!/usr/bin/env bash
# Generated by slurm_run_grism.sh at $(date -Iseconds).
# Project: ${PROJ_ROOT}
# Acceptance run: ${ACCEPT_DIR}
# One SLURM array task = one Python process owning a round-robin share
# of pointings (--worker-index = TASK_ID-1, --num-workers = ${NUM_WORKERS}).
# Per-pointing skip-if-exists makes restarts cheap.
set -euo pipefail
WORKER_INDEX=\$((SLURM_ARRAY_TASK_ID - 1))
LOG_FILE=${ACCEPT_DIR}/logs/worker-\${SLURM_ARRAY_TASK_ID}.log
exec pixi run --manifest-path ${PROJ_ROOT}/pixi.toml -e cuda \\
    python ${PROJ_ROOT}/scripts/build_grism_image.py \\
        --config ${CONFIG} \\
        --pointings ${ECSV} \\
        --cache-dir ${CACHE_DIR} \\
        --gpu 0 \\
        --worker-index \${WORKER_INDEX} \\
        --num-workers ${NUM_WORKERS} \\
        --log-file \${LOG_FILE}
EOF
chmod +x "$TASK_WRAPPER"

JOB=$(sbatch --parsable \
    --partition="$PART" --gres="$GRES" --cpus-per-task=4 --mem="$MEM" --time="$TIME" \
    --array="1-${NUM_WORKERS}%${NUM_WORKERS}" --job-name=acc-grism \
    --output="${SLURM_LOG}/%A_%a.out" \
    "$TASK_WRAPPER")

# Audit record under slurm-meta/.
META="${META_DIR}/grism-${JOB}"
cp "$TASK_WRAPPER" "${META}.task.sh"
{
    echo "JOB=$JOB"
    echo "ARRAY=1-${NUM_WORKERS}"
    echo "NUM_WORKERS=$NUM_WORKERS"
    echo "PARTITION=$PART"
    echo "GRES=$GRES"
    echo "MEM=$MEM"
    echo "TIME=$TIME"
    echo "CONFIG=$CONFIG"
    echo "ECSV=$ECSV"
    echo "CACHE_DIR=$CACHE_DIR"
    echo "PROJ_ROOT=$PROJ_ROOT"
    echo "GIT_COMMIT=$(git -C "$PROJ_ROOT" rev-parse HEAD 2>/dev/null || echo NA)"
    echo "SLURM_LOG_DIR=$SLURM_LOG"
    echo "SUBMITTED_AT=$(date -Iseconds)"
} > "${META}.env"

echo "submitted JobID=${JOB} (array 1-${NUM_WORKERS}, partition=${PART}, gres=${GRES}, mem=${MEM}, time=${TIME})"
echo "  task wrapper: ${TASK_WRAPPER}"
echo "  audit:        ${META}.env"
echo "  scheduler logs: ${SLURM_LOG}/${JOB}_*.out"
echo "  per-worker logs: ${ACCEPT_DIR}/logs/worker-N.log"
echo "  monitor:      squeue -j ${JOB}"
