#!/usr/bin/env bash
# Spectro acceptance SLURM driver: submit build_grism_image.py as a 32-task
# array, one pointing per task, on the gpu-med partition (a10g).
#
# Layout assumed (relative to this script):
#   ../config.yaml                                    # --config
#   ../../../acceptance-testing-spectro.sim.ecsv      # --pointings (top of accept-test-20260430)
#   ../slurm-meta/                              # per-submission audit
#
# Each task runs build_grism_image.py with --worker-index=$TASK_ID-1 and
# --num-workers=32, so each pointing maps deterministically to one task.
# RNG keys are derived from (seed, ECSV basename, APT identifiers) so the
# array partitioning has no effect on output.
#
# Env-var hooks (all optional):
#   SUBSET            sbatch --array spec, default "1-N" where N = ECSV row count.
#                     Use e.g. SUBSET=31 to validate one pointing (row 31 = 016.001).
#   MAX_CONCURRENT    --array=...%K, default 5 (matches gpu-med a10g node count).
#   PARTITION         default gpu-med
#   GRES              default gpu:a10g:1 (g5-2xlarge: 4 CPU, 31 GB, a10g)
#   MEM               default 24G (leaves ~7 GB margin on the 31 GB node)
#   TIME              default 02:30:00. From debug-grism-nan/repro_after_fix.log
#                     on this a10g: 1 SCA = 390 s cold (169 s JIT + 221 s compute)
#                     or ~240 s warm (15 s JIT + 221 s compute). 18 SCAs/pointing
#                     -> ~70 min warm, ~120 min cold. 2.5 h leaves ~30 min margin.
#   PROJ_ROOT         default /data/npadman/1-Projects/roman_disperser
#
# Per-submission audit: ../slurm-meta/grism-<JobID>.{task.sh,env}
# Scheduler stdout:     /data/npadman/tmp/slurm-logs/grism/%A_%a.out
#
# Usage: slurm_run_grism.sh
set -euo pipefail

ACCEPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
CONFIG="${ACCEPT_DIR}/config.yaml"
ECSV="$(cd "${ACCEPT_DIR}/../../.." && pwd)/acceptance-testing-spectro.sim.ecsv"
META_DIR="${ACCEPT_DIR}/slurm-meta"
SLURM_LOG=/data/npadman/tmp/slurm-logs/grism
# Explicit cache dir: shared across all 32 array tasks + the warmup pre-pass.
# Pulling it out of YAML and onto the CLI makes it visible in audit + scheduler logs.
CACHE_DIR=/data/npadman/jax-cache-grism

[ -f "$CONFIG" ] || { echo "missing $CONFIG"; exit 1; }
[ -f "$ECSV" ]   || { echo "missing $ECSV"; exit 1; }

PROJ_ROOT="${PROJ_ROOT:-/data/npadman/1-Projects/roman_disperser}"
[ -f "${PROJ_ROOT}/pixi.toml" ] || { echo "no pixi.toml under PROJ_ROOT=${PROJ_ROOT}"; exit 1; }
mkdir -p "$CACHE_DIR"

# Count GRISM-bandpass rows in the ECSV (skip ECSV header + col-name line).
# build_grism_image.py filters BANDPASS != GRISM, but the ECSV is already
# all-GRISM, so total row count = 32 = num-workers.
N=$(awk 'NR==1{next} /^#/{next} NR==FNR && !seen{seen=1; next} {n++} END{print n+0}' "$ECSV")
[ "$N" -gt 0 ] || { echo "could not parse row count from $ECSV"; exit 1; }

ARR="${SUBSET:-1-${N}}"
K="${MAX_CONCURRENT:-5}"
PART="${PARTITION:-gpu-med}"
GRES="${GRES:-gpu:a10g:1}"
MEM="${MEM:-24G}"
TIME="${TIME:-02:30:00}"

mkdir -p "$META_DIR" "$SLURM_LOG"

# Per-submission task wrapper. Backslashed $ are deferred to runtime; bare $
# expand at submit time so the on-disk wrapper is self-contained.
TS=$(date +%Y%m%dT%H%M%S)
TASK_WRAPPER="${META_DIR}/_grism_array_task_${TS}.sh"
cat > "$TASK_WRAPPER" <<EOF
#!/usr/bin/env bash
# Generated by slurm_run_grism.sh at $(date -Iseconds).
# Project: ${PROJ_ROOT}
# Acceptance run: ${ACCEPT_DIR}
# One SLURM array task = one pointing (--worker-index=TASK_ID-1).
set -euo pipefail
WORKER_INDEX=\$((SLURM_ARRAY_TASK_ID - 1))
LOG_FILE=${ACCEPT_DIR}/logs/pointing-\${SLURM_ARRAY_TASK_ID}.log
exec pixi run --manifest-path ${PROJ_ROOT}/pixi.toml -e cuda \\
    python ${PROJ_ROOT}/scripts/build_grism_image.py \\
        --config ${CONFIG} \\
        --pointings ${ECSV} \\
        --cache-dir ${CACHE_DIR} \\
        --gpu 0 \\
        --worker-index \${WORKER_INDEX} \\
        --num-workers ${N} \\
        --log-file \${LOG_FILE}
EOF
chmod +x "$TASK_WRAPPER"

JOB=$(sbatch --parsable \
    --partition="$PART" --gres="$GRES" --cpus-per-task=4 --mem="$MEM" --time="$TIME" \
    --array="${ARR}%${K}" --job-name=acc-grism \
    --output="${SLURM_LOG}/%A_%a.out" \
    "$TASK_WRAPPER")

# Audit record under slurm-meta/.
META="${META_DIR}/grism-${JOB}"
cp "$TASK_WRAPPER" "${META}.task.sh"
{
    echo "JOB=$JOB"
    echo "ARRAY=$ARR"
    echo "MAX_CONCURRENT=$K"
    echo "PARTITION=$PART"
    echo "GRES=$GRES"
    echo "MEM=$MEM"
    echo "TIME=$TIME"
    echo "CONFIG=$CONFIG"
    echo "ECSV=$ECSV"
    echo "ECSV_ROWS=$N"
    echo "CACHE_DIR=$CACHE_DIR"
    echo "PROJ_ROOT=$PROJ_ROOT"
    echo "GIT_COMMIT=$(git -C "$PROJ_ROOT" rev-parse HEAD 2>/dev/null || echo NA)"
    echo "SLURM_LOG_DIR=$SLURM_LOG"
    echo "SUBMITTED_AT=$(date -Iseconds)"
} > "${META}.env"

echo "submitted JobID=${JOB} (array ${ARR}, K=${K}, partition=${PART}, gres=${GRES}, mem=${MEM})"
echo "  task wrapper: ${TASK_WRAPPER}"
echo "  audit:        ${META}.env"
echo "  scheduler logs: ${SLURM_LOG}/${JOB}_*.out"
echo "  per-pointing logs: ${ACCEPT_DIR}/logs/pointing-N.log"
echo "  monitor:      squeue -j ${JOB}"
